name: Java CI

on:
  workflow_dispatch: { }
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    # No automatic builds for Dependabot PRs
    # Caveat: cannot start 'if:' expression with '!', hence '!= true'
    if: startsWith(github.actor, 'dependabot') != true

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        javaVersion: [ 8, 11, 17 ]
        gebEnv: [ chrome_headless, firefox_headless, html_unit ]
        exclude:
          # Both Firefox install actions I tried are currently not working on Windows, see
          #   * https://github.com/browser-actions/setup-firefox/issues/252
          #   * https://github.com/abhi1693/setup-browser/issues/8
          - os: windows-latest
            gebEnv: firefox_headless
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

      - name: Set Git options
        # Check out as-is, commit Unix-style line endings
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/de/scrum-master/geb-spock-*
            ~/.cache/selenium
          key: maven-${{ matrix.os }}-java${{ matrix.javaVersion }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.javaVersion }}-
            maven-${{ matrix.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: temurin

      - name: Set up Chrome browser
        if: ${{ matrix.gebEnv  == 'chrome_headless' }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Set up Firefox browser
        # This action is currently not working on Windows,
        # see https://github.com/browser-actions/setup-firefox/issues/252
        if: ${{ matrix.gebEnv == 'firefox_headless' && matrix.os != 'windows-latest' }}
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest

      - name: Set up Firefox browser
        # Fill the gap left behind by browser-actions/setup-firefox, at least temporarily,
        # see https://github.com/browser-actions/setup-firefox/issues/252
        if: ${{ matrix.gebEnv == 'firefox_headless' && matrix.os == 'windows-latest' }}
        uses: abhi1693/setup-browser@main
        with:
          browser: firefox
          version: latest

      - name: Print tool versions
        # TODO: 'chrome --version' must be 'chromium --version' on MacOS
        run: |
          java -version
          mvn --batch-mode --version

      - name: Build with Maven
        # Chrome Headless, Firefox Headless and HtmlUnit do not need Xvfb.
        # TODO: When also using other browsers, we need Xvfb on Linux.
        run: mvn -U --batch-mode -P github -fae "-Dgeb.env=${{ matrix.gebEnv }}" "-Dwdm.gitHubToken=${{ secrets.GITHUB_TOKEN }}" clean verify

      # No matter if a preceding test run failed or not, try to generate and upload a test report
      # TODO: these steps should only happen if at least the build without tests passed, not always

      - name: Generate aggregate test reports
        if: always()
        run: mvn --batch-mode -P github -Daggregate=true surefire-report:report-only surefire-report:failsafe-report-only

      - name: Attach aggregate test report to build
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report-${{ matrix.os }}-java${{ matrix.javaVersion }}-${{ matrix.gebEnv }}
          path: target/site/*-report.html
